# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aveula Redes
email: aveula@aveula.com
description: >- # this means to ignore newlines until "baseurl:"
  Aveula Redes está diseñada para dar servicio a las empresas, resolviendo sus problemas de focalización, bien en mercados que al no ser conocidos, o bien en temas que por ser muy específicos, no están cualificados para resolver, y necesitan de alguien de confianza que les aporte conocimientos y trabajo donde ellos no llegan.

  Contamos con personal de máxima confianza y con contrastada experiencia, que, en la mayoría de los casos, superan los 20 años de experiencia en sus sectores, y lo que es más importante, la capacidad de resolver cualquier problema en tiempo y forma ágil y flexible.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
remote_theme: Aveula/twd-jt-aveula-sg
plugins:
  - jekyll-feed
include:
  - _pages

# Collections
collections_dir: content
collections:
  paginas:
    output: true
  tarifas:
  servicios:
    output: true
  franquicia:
  negocio:
  trabajo:
  traspaso:
  principios:
  testimonios:
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      path: ""
      type: servicios
    values:
      layout: service
      hide_content: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
