backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"

collections:
  - label: "Blog en Español"
    name: "spanish_posts"
    folder: "_posts/es"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "language", value: "es"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Blog en Inglés"
    name: "english_posts"
    folder: "_posts/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Blog en Alemán"
    name: "deutsch_posts"
    folder: "_posts/de"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "language", value: "de"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Data"
    name: "data"
    files:
      - label: "Menú principal"
        name: "mainMenu"
        file: "_data/main-menu.yml"
        fields:
          - label: Items
            name: items
            widget: "list"
            fields:
              - {label: Language, name: lang,widget: string}
              - label: Item
                name: item
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Url, name: url, widget: string}

      - label: "Contratación"
        name: "contratacion"
        file: "_data/contratacion.yml"
        fields:
          - label: Items
            name: items
            widget: "list"
            fields:
              - {label: Language, name: lang, widget: string}
              - {label: Texto, name: texto, widget: string}


  - label: "Tarifas en Español"
    name: "spanish_pricing"
    folder: "_tarifas/es"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "es"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - {label: "Orden", name: "order", widget: "number", default: 0, valueType: "int"}
      - label: "Tarifas incluidas"
        name: "price_included"
        widget: "list"
        required: false
        fields:
          - {label: "Tarifa", name: "name", widget: "string"}
      - label: Item
        name: item
        widget: list
        fields:
          - {label: "Description", name: "description", widget: string}

  - label: "Tarifas en Inglés"
    name: "english_pricing"
    folder: "_tarifas/en"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - {label: "Orden", name: "order", widget: "number", default: 0, valueType: "int"}
      - label: "Tarifas incluidas"
        name: "price_included"
        widget: "list"
        required: false
        fields:
          - {label: "Tarifa", name: "name", widget: "string"}
      - label: Item
        name: item
        widget: list
        fields:
          - {label: "Description", name: "description", widget: string}

  - label: "Tarifas en Alemán"
    name: "deutsch_pricing"
    folder: "_tarifas/de"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "de"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - {label: "Orden", name: "order", widget: "number", default: 0, valueType: "int"}
      - label: "Tarifas incluidas"
        name: "price_included"
        widget: "list"
        required: false
        fields:
          - {label: "Tarifa", name: "name", widget: "string"}
      - label: Item
        name: item
        widget: list
        fields:
          - {label: "Description", name: "description", widget: string}

  - label: "Servicios en Español"
    name: "spanish_services"
    folder: "_servicios/es"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "es"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "permalink", name: "permalink", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - label: "Paquetes"
        name: "paquetes"
        widget: list
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Contratación", name: "contratacion", widget: "markdown"}

  - label: "Servicios en Inglés"
    name: "english_services"
    folder: "_servicios/en"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "permalink", name: "permalink", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - label: "Paquetes"
        name: "paquetes"
        widget: list
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Contratación", name: "contratacion", widget: "markdown"}

  - label: "Servicios en Alemán"
    name: "deutsch_services"
    folder: "_servicios/de"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "de"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "permalink", name: "permalink", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "language", widget: "select", options: ["es", "en", "de"]}
      - label: "Paquetes"
        name: "paquetes"
        widget: list
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Contratación", name: "contratacion", widget: "markdown"}
